Correct b2.toml
rustic-rs/rustic pull request #1072
Opened 2024-02-19 08:14 UTC by HaleTom

- s/key_id/application_key_id/
- Remove generic opendal comment
- Add comment for password file
- Add comment for OpenDAL environment variables

2024-02-19 08:27 UTC, HaleTom commented
Related:

rustic: OPENDAL_B2_* variables don't work #1073
https://github.com/rustic-rs/rustic/issues/1073

opendal: Do OPENDAL_B2_* environment variables work? #4199
https://github.com/apache/opendal/issues/4199

2024-02-19 21:18 UTC, aawsome requested changes
Thanks @HaleTom for the PR! I have only minor change requests.

2024-02-19 21:18 UTC, aawsome commented on config/services/b2.toml
> +# password-file = "/home/<username>/etc/secure/restic_passwd"
maybe name it `rustic_passwd`? People using restic for sure will know that they can also use the restic password file here.

2024-02-19 21:18 UTC, aawsome commented on config/services/b2.toml
> +# - Issue pending: https://github.com/rustic-rs/rustic/issues/1073
Please remove it here. Once we takle #1073 we can add it. Current state is it isn't available through env variables.

2024-02-25 10:33 UTC, aawsome approved these changes
Thanks a lot @HaleTom

2024-02-25 10:34 UTC, merged