allow request for new key to confirm entered pass
rustic-rs/rustic pull request #702
Opened 2023-06-23 12:23 UTC by Aderemi-Adesada

allow request for new key to prompt user to confirm the password they entered

2023-06-23 14:31 UTC, istudyatuni commented
Maybe move these closures to separate function?

2023-06-23 15:06 UTC, Aderemi-Adesada commented
What is the best file to add the function so that both key.rs and init.rs can access

2023-06-23 15:27 UTC, aawsome commented
First, this PR IMO doesn't allow to confirm the password, but enforces it.
I personally wouldn't need that, but if you think this is a worthwhile addition, I'm open for it ;-)

About the place: Please not in `rustic_core`. This crate provides core functionality to access repositories and perform operations on it. All UI topics should stay outside - and this is for sure just a UI topic!

2023-06-23 16:41 UTC, Aderemi-Adesada commented
@istudyatuni @aawsome  what do you think about having a function called prompt_password_twice in rustic/src/helpers that both init.rs and key.rs can call

2023-06-23 20:01 UTC, istudyatuni commented
I'm afraid to make those decisions in this project 😁

2023-06-24 04:07 UTC, aawsome commented
As discussed @Aderemi-Adesada on discord, I also think that the best idea is to replace `rpassword`  with `dialoguer` which already implements this functionality.

2023-06-24 11:37 UTC, Aderemi-Adesada commented
rpassword has been replaced with dialoguer in init.rs and key.rs when prompting for new key

2023-06-25 02:40 UTC, aawsome requested changes
Beside my remarks, I was wondering if we can remove the dependency on `rpassword` completely. Then I remembered some newline handling which needed to be dealt with.
Checking the code I realized that that fix already removed `rpassword` when reading from a file - but obviously I have overseen this in `src/command/key.rs`. Can you please have a look at `read_password_from_reader` in `rates/rustic_core/src/repository.rs` and use this in  `src/command/key.rs` - this should allow to remove `rpassword` completely.

Moreover, can you please add an entry in `changelog/new.txt` and after your changes squash all commits into 1 commit? Thanks a lot!

2023-06-25 02:40 UTC, aawsome commented on src/commands/init.rs
> +            password
No need for new variables which are immediately used in the next command. You can use `match Password::new() ... { ... }` here.

2023-06-25 02:40 UTC, aawsome commented on src/commands/init.rs
> +                .with_confirmation("confirm password", "passwords do not match")
According to the documentation you have to enable empty passwords explicitly. These are currently supported by rustic, so please add `allow_empty_password(true)`.

2023-06-25 08:05 UTC, Aderemi-Adesada commented
rpassword have been removed completely and `src/command/key.rs` now uses `read_password_from_reader` as used in `crates/rustic_core/src/repository.rs`

2023-06-25 09:21 UTC, aawsome commented
@Aderemi-Adesada there are syntax errors in `lib.rs` - can you have a look at it?

2023-06-25 09:27 UTC, Aderemi-Adesada commented
> syntax error

I will fix that right now

2023-06-25 09:51 UTC, Aderemi-Adesada commented
syntax error have been fixed

2023-06-25 18:18 UTC, aawsome commented
Can you please rebase to main and squash all commits instead of re-merging master back into your branch? That will keep commit history clean. Thanks a lot!

2023-06-25 19:56 UTC, merged

2023-06-25 19:58 UTC, aawsome commented
Oh, clicked wrong - actually wanted to run the tests.
Anyway, we'll see in the CI. Thanks a lot @Aderemi-Adesada - looks good to me!

2023-06-25 19:59 UTC, Aderemi-Adesada commented
You are welcome